# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/

node_js: stable #设置相应的版本

before_install:
  - npm install hexo-cli -g
  - npm install gulp -g
  - npm install #安装hexo及插件
  
install:
    # get more infomation
    - ls
    - pwd
    - hexo version
    - curl -V 

script:
    - hexo clean && hexo generate && gulp build
    - \cp ./source/_config.yml ./themes/next/_config.yml
    - cd ./public
    - git init
    - git config user.name "TianlongXiang"
    - git config user.email "tianlongxiang51@gmail.com"
    - git add .
    - git commit -m "Update TianlongXiang's Blog"
    - git push --force --quiet "https://${GH_TOKEN}@github.com/irsunshine/irsunshine.github.io.git" master:master
    - cd ..
    - ls
    - pwd
    - hexo clean && hexo generate && gulp build
    - \cp ./source/_config.yml ./themes/next/_config.yml
    - cd ./public
    - git init
    - git config user.name "TianlongXiang"
    - git config user.email "tianlongxiang51@gmail.com"
    - git add .
    - git commit -m "Update TianlongXiang's Blog"
    - git push --force "https://xiangtianlong:${GITEE_PASSWORD}@gitee.com/xiangtianlong/xiangtianlong.git" master:master
    - echo 'Hexo build done!'

after_script:
    - ls
    - pwd
    - curl -H 'Content-Type:text/plain' --data-binary @baidu_urls.txt "http://data.zz.baidu.com/urls?site=xiangtianlong.com&token=${BAIDU_TOKEN}"

branches:
  only:
    - hexo

env:
  global:
    secure: aJvy7UZkLuDGawIZHvCajqksGIYeCvjbygEq5mSCtUp9TJ+ukUMxtYYfgOUutpHkhJsc7tUTTrLRTxs1K/npgTTQINJS+AWrhsA09S53iEZY6VxcWN/1E8aEqQYmOwWAOuqnu8yKXuftcerBeQk41FHzW0Q9h2fB+M2FcSp3zcQdWaKIibVG5dZJt38SlmwNsCXGJki9E9BGjWTnMcZgDfw2/rObbCCgZWpaXe/Xmk1z+qirVr8nZSmwvOzPgc0CZ6d7CdNZXEgOpdHyEIN1OuEtLE0nCnlaiWUkg2vgKA4whbGaUiOLERTqMFcYKh9hOHnW8P4WcvPMe1R5jtM1LPsD9r1ELBai55u8r+a5KGpKT7TSfuJnHwCjh56TuxSTdYahbHjlC0nsMwJ6Nt7Zl+XD4XLExfS38nqMqikEUr4J53Chh32KW4R26RmtM0wip0EFi4ce/X3ptZoNCx2ddIZA8ILGUhJdnnH/pOWstB6zyhHzTXxcHVYsnYdvyeVJn3Gs6yEFl2xgO/hfBz+mvJwjHKrTwnqRgYVInqk/Rwq0fhMIPx6RYvIbTUlPXSqCKDqK155XqMto+87/aK6HHpn4F79dGEnV8BWJK5YM/qwbzF8YMSrgAwXD8ISq63B/972CyGHL537WYUAbZHuPuhuifsS9J7Mj+qEZTU1bMiw=