# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

before_install:
  # This workaround is required to avoid libstdc++ errors while running "extended" hugo with SASS support.
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
  
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_extended_0.55.6_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    # get more infomation
    - ls
    - pwd

script:
    - hugo -b "http://www.xiangtianlong.com/" -d "gitee_public"
    - hugo -b "http://www.xiangtianlong.com/" -d "github_public"
    - echo 'Hugo build done!'
    
after_script:
- cp ./static/baidu_verify_Bc279j6L6W.html ./github_public
- cp ./static/CNAME ./github_public
- cp ./static/baidu_verify_Bc279j6L6W.html ./gitee_public
- cp ./static/_variables.scss ./themes/coder/assets/scss
- cd ./github_public
- git init
- git config user.name "TianlongXiang"
- git config user.email "tianlongxiang51@gmail.com"
- git add .
- git commit -m "Update TianlongXiang's Blog"
- git push --force --quiet "https://${GH_TOKEN}@github.com/irsunshine/irsunshine.github.io.git" master:master
- cd ..
- ls
- pwd
- cd ./gitee_public
- git init
- git config user.name "TianlongXiang"
- git config user.email "tianlongxiang51@gmail.com"
- git add .
- git commit -m "Update TianlongXiang's Blog"
- git push --force "https://xiangtianlong:${GITEE_PASSWORD}@gitee.com/xiangtianlong/xiangtianlong.git" master:master

branches:
  only:
    - hugo-academic

env:
  global:
    secure: aJvy7UZkLuDGawIZHvCajqksGIYeCvjbygEq5mSCtUp9TJ+ukUMxtYYfgOUutpHkhJsc7tUTTrLRTxs1K/npgTTQINJS+AWrhsA09S53iEZY6VxcWN/1E8aEqQYmOwWAOuqnu8yKXuftcerBeQk41FHzW0Q9h2fB+M2FcSp3zcQdWaKIibVG5dZJt38SlmwNsCXGJki9E9BGjWTnMcZgDfw2/rObbCCgZWpaXe/Xmk1z+qirVr8nZSmwvOzPgc0CZ6d7CdNZXEgOpdHyEIN1OuEtLE0nCnlaiWUkg2vgKA4whbGaUiOLERTqMFcYKh9hOHnW8P4WcvPMe1R5jtM1LPsD9r1ELBai55u8r+a5KGpKT7TSfuJnHwCjh56TuxSTdYahbHjlC0nsMwJ6Nt7Zl+XD4XLExfS38nqMqikEUr4J53Chh32KW4R26RmtM0wip0EFi4ce/X3ptZoNCx2ddIZA8ILGUhJdnnH/pOWstB6zyhHzTXxcHVYsnYdvyeVJn3Gs6yEFl2xgO/hfBz+mvJwjHKrTwnqRgYVInqk/Rwq0fhMIPx6RYvIbTUlPXSqCKDqK155XqMto+87/aK6HHpn4F79dGEnV8BWJK5YM/qwbzF8YMSrgAwXD8ISq63B/972CyGHL537WYUAbZHuPuhuifsS9J7Mj+qEZTU1bMiw=