# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

before_install:
  # This workaround is required to avoid libstdc++ errors while running "extended" hugo with SASS support.
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
  
install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf public
    # get more infomation
    - ls
    - pwd

script:
    - hugo -b "https://irsunshine.gitee.io/" -d "gitee_public"
    - hugo -b "https://irsunshine.github.io/" -d "github_public"
    - echo 'Hugo build done!'
    
after_script:
- cd ./github_public
- git init
- git config user.name "TianlongXiang"
- git config user.email "tianlongxiang51@gmail.com"
- git add .
- git commit -m "update"
- git push --force --quiet "https://${GH_TOKEN}@github.com/irsunshine/irsunshine.github.io.git" master:master
- cd ..
- ls
- pwd
- cd ./gitee_public
- git init
- git config user.name "TianlongXiang"
- git config user.email "tianlongxiang51@gmail.com"
- git add .
- git commit -m "update"
- git push --force --quiet "https://${GITEE_TOKEN}@gitee.com/irsunshine/irsunshine.git" master:master

branches:
only:
- hugo