#集成命令中，通过 -b 设置，便于同步提交两个 git remote
baseURL = "https://irsunshine.github.io/"

languageCode = "zh-cn"

title = "假装不困"

theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleanalytics = "UA-110120845-1"

[permalinks]
    posts = "/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"   

[params]
    author = "某人"
    avatarurl = "images/avatar.jpg"
    info = "疯子，程序开发，中二少年"
    description = "你才二十岁，你可以成为任何你想成为的人"
    keywords = "博客, 程序开发, C++"

    inverted = false
    custom_css = ["css/custom.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/irsunshine"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss-square"
    weight = 2
    url = "/index.xml"

[[menu.main]]
    name = "归档"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "分类"
    weight = 2
    url  = "/categories/"
[[menu.main]]
    name = "标签"
    weight = 3
    url  = "/tags/"
[[menu.main]]
    name = "关于我"
    weight = 4
    url = "/about/"
[[menu.main]]
    name = "关于博客"
    weight = 5
    url = "/article/"